hints_and_answers = {
    "One of two men depicted kissing on the Berlin Wall": "Brezhnev",
    "Bavarian festival celebrated annually": "Oktoberfest",
    "A woodsy desert": "BlackForrestCake",
    "'That's the end of my ___'": "Spiel",
    "A forcing position in a game of chess": "Zugzwang",
    "Discoverer of X-ray radiation": "Roentgen",
    "The feeling of needing to go out and explore nature": "Wanderlust",
    "The world's most famous techno club": "Berghain",
    "Wealthiest per capita neighbor": "Luxembourg",
    "Spanish island overrun by German tourists": "Mallorca",
    "Writer of the play 'Faust'": "Goethe",
    "A traditional Berlin food": "Currywurst",
    "The tallest German mountain": "Zugspitze",
    "Hill housing a cold-war era spy station": "Teufelsberg",
    "A place known for its lack of speed-limits": "Autobahn",
    "President who said 'Mr. Gorbachev, tear down this wall.'": "Ronald Reagan",
    "A necessary stop on the passage from East to West": "Checkpoint Charlie",
    "Biblical garden which lends its name to our neighborhood church": "Gethsemane",
    "Automobile insect": "VW Bug",
    "Tennis champion with 22 grand slam titles": "Steffi Graf",
    "Film studio near Potsdam": "Babelsberg",
    "Eccentric German designer, iconic for his ponytail and black sunglasses": "Lagerfeld",
    "Star of 'The Blue Angel', 'Morocco', and 'Shanghai Express'": "Marlene Dietrich",
}